version: '3.8'
services:
  app:
    build: .
    container_name: node-app
    ports:
      - 4000:4000

    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: express_api
    volumes:
      - .:/var/www
      - /var/www/node_modules  # Evita que os módulos sejam sobrescritos pelo volume local
 
     
    working_dir: /var/www
    
    #command: npm run dev 
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_api
    volumes:
      - db_data:/var/lib/mysql
    ports:
        - 3309:3306
volumes:
  db_data:


    