const express=require("express")
const auth=require("../middlewares/auth") 
const rota=express.Router()
const projectoController = require('../Controller/projectoController')
const tarefaController=require("../Controller/tarefaController")
const TipoProjectoController = require("../Controller/tipoProjectoController")
rota.get("/projectos",projectoController.todosProjectos)
rota.post("/projectos",projectoController.criarProjectos)
rota.put("/projectos/:id",projectoController.editarProjectos)
rota.delete("/projectos/:id",projectoController.apagarProjectos)
rota.get("/progectos-tarefas/:id",projectoController.projectosTarefas)
rota.get("/todastarefa",auth.autenticar,tarefaController.todasTarefa)
rota.post("/crear_tarefa",tarefaController.crearTarefa)
rota.put("/tarefa/:id",auth.autenticar,tarefaController.editaTarefa)
rota.delete("/tarefa/:id",tarefaController.apagarTarefa)
rota.get("/tipo_projecto",TipoProjectoController.todosTipoProjecto)
//routers.use("/",tarefaController)
module.exports=rota